### PR TITLE
bug: decoding error with constants

### LINKED ISSUE #54: feat: debug decode_instruction for 0x40780017fff7fff
This instruction returns constant value `290341444919459839` while it should be

memory | opcode | off0 | off1 | off2 | dst | op0 | op1 | res | pc_update | ap_update | fp_update
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0x40780017fff7fff | NOp | -1 | -1 | 1 | FP | FP | Imm | Op1 | Regular | Add | Regular

(see also cairovm.codes)

```python
from starkware.cairo.lang.compiler.encode import decode_instruction

decode_instruction(0x40780017fff7fff, 1)
# Instruction(off0=-1, off1=-1, off2=1, imm=1, dst_register=<Register.FP: 1>, op0_register=<Register.FP: 1>, op1_addr=<Op1Addr.IMM: 0>, res=<Res.OP1: 0>, pc_update=<PcUpdate.REGULAR: 0>, ap_update=<ApUpdate.ADD: 1>, fp_update=<FpUpdate.REGULAR: 0>, opcode=<Opcode.NOP: 0>)

### PR DESCRIPTION
**Pull request by AntoineFONDEUR**
bug: decoding error with constants

Time spent on this PR: 45 mins

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Currently an instruction is interpreted as a felt constant as long as it is a NOp and has a regular PCUpdate.

Resolves #54 

## What is the new behavior?

There is no way to make a difference between a felt constant and an instruction.
So the new behavior is to try to decode all instructions and no matter if it fails or not, it will convert the instruction to a decimal number in the right column.

### CODE REVIEW

**Review by ClementWalter — CHANGES_REQUESTED** [review]
I suggest that we instead try to use the `size` of an instruction. If a given instruction is size = 2, then the following encoded instruction is a constant. Otherwise, we try to decode as an instruction, and if an error is raised, again, consider it's a constant

File: src/ui/ui.ts [hunk 1]
```diff
@@ -42,14 +42,25 @@ function showPicker() {
...
+            ? `=TO_SIGNED_INTEGER(A${i + 2})`
+            : `=DECODE_INSTRUCTION(A${i + 2})`,
+        ],
+      ]);
+    if (!isConstant) {
+      isConstant = size(decodeInstruction(BigInt(bytecode[i]))) == 2;
+    } else {
+      isConstant = false;
+    }
+  }
```
Comment (ClementWalter) [inline src/ui/ui.ts:62]: when possible, I prefer not to use "stateful" for loops, ie loops where an iteration depends on the previous ones.
```suggestion
  programSheet
    .getRange(`A2:B${bytecode.length + 1}`)
    .setValues(
      bytecode.map((instruction, i) => [
        instruction,
        i > 0 && size(decodeInstruction(BigInt(bytecode[i - 1]))) == 2 ? `=TO_SIGNED_INTEGER(A${i + 2})` : `=DECODE_INSTRUCTION(A${i + 2})`,
      ]),
    );
```

Comment (ClementWalter) [reply src/ui/ui.ts:62]: of course we compute two times `decodeInstruction` here so it's probably less efficient.

**Review by ClementWalter — APPROVED** [review]
